# Generated by Django 3.1.6 on 2021-02-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('serial_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_json', models.JSONField()),
            ],
        ),
    ]
